### ISSUE TITLE
USER STORY: Hide the poll

### ISSUE THREAD

**Issue by andrezeitz** [andrezeitz/love-running#5]
In order to **automatically hide the poll** as a **admin**, I can **pick the expiry date while publishing the poll**

# Acceptance Criteria
* The poll should disappear at 11.59PM
* The real estate of the poll should be reseved on the homepage
* The admin expiry date should be at least 3 days

# Tasks
- [x] Update the admin module
- [x] Update the website view
- [ ] Update the text scripts
- [ ] Test the functionality
